### ISSUE TITLE
Peer feedback W3

### ISSUE THREAD

**Issue by lars-ruijs** [kilroy763/web-app-from-scratch-2021#5]
### ✅ Done
- [X] Description in the README
- [X] Link to live preview in the README
- [X] Repository is open for issues
- [X] Repo includes a .gitignore
- [X] Includes Actor and Interaction diagrams
- [X] Includes information about the data (API) that is used. 

### 📌 To-do
- [x] Add a short description of your app in the about section. 
- [x] Change the link in the about section to the live preview of your own app. 
- [ ] If applicable, add used sources to your README.

## Actor & Interaction Diagram
It looks like you changed your app structure and re-named some functions, however the Actor and Interaction Diagrams don’t seem updated.

### 📌 To-do
- [x] Update your Actor Diagram with your renewed app structure.
- [x] Update your Interaction Diagram with your renewed app structure.

### ✅ Done
- [X] The preview looks nice! ✨ 
- [X] The interaction works like expected.
- [X] It renders a detail page on click.
- [X] You are already integrating a photo editor which is working!!

### 📌 Improvements
- [ ] You could add a loading animation as user feedback. 
- [ ] You could improve the styling of the detailpage (center the poster image and improve the background image).

### ✅ Done
- [X] The code has been structured into modules
- [X] Logical names for most functions and variables. 

### 📌 Improvements
- [x] Check if it is possible to combine the fetch functions into one function. 
- [ ] I did not find any map, filter or reduce functions.
